# Example inventory file for GoldenGate deployment
# This can be customized for your environment

all:
  vars:
    # GoldenGate Server Configuration
    ogg_url: "https://ogg-server:9011"
    ogg_username: "admin" 
    ogg_password: "{{ vault_ogg_password }}"
    ogg_validate_certs: false
    
    # Source Database Configuration
    source_host: "source-db.example.com"
    source_port: 1521
    source_service: "ORCL"
    source_alias: "SOURCEDB"
    
    source_host_2: "source-db2.example.com"
    source_port_2: 1521
    source_service_2: "ORCL2" 
    source_alias_2: "SOURCEDB2"
    
    # Target GoldenGate Servers
    target_ogg_server: "remote-ogg.example.com"
    target_ogg_server_port: 9021
    
    target_ogg_server_2: "remote-ogg2.example.com"
    target_ogg_server_port_2: 9021
    
    # Target Database Configuration
    target_host: "target-db.example.com"
    target_port: 1521
    target_service: "TGTDB"
    target_alias: "TARGETDB"
    
    target_host_2: "target-db2.example.com"
    target_port_2: 1521
    target_service_2: "TGTDB2"
    target_alias_2: "TARGETDB2"

  hosts:
    localhost:
      ansible_connection: local